[tool.semantic_release]
version_variable = "notebooks/01_ingest_qualite_eau/__init__.py:__version__"
commit_parser = "angular"
changelog_file = "CHANGELOG.md"
branch = "main"
upload_to_pypi = false
upload_to_release = true
