name: Ingest DataGouv -> Azure Blob

on:
  workflow_dispatch: {}              # lancement manuel
  # schedule:
  #   - cron: "30 5 * * 1"            # tous les lundis à 05:30 UTC (07:30 Paris)

concurrency:
  group: ingest-data
  cancel-in-progress: false

jobs:
  run-ingest:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    env:
      # Expose le secret comme variable d'env pour le script
      AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
      # (optionnel) HTTP(S) proxy d'entreprise
      # HTTP_PROXY: ${{ secrets.HTTP_PROXY }}
      # HTTPS_PROXY: ${{ secrets.HTTPS_PROXY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install azure-storage-blob requests

      - name: Run ingest script
        working-directory: ingest_azure   # <-- adapte si ton script est ailleurs
        run: |
          python -V
          python 01_ingest_data.py

      # Optionnel : sauvegarder un petit journal (utile en cas d’échec)
      - name: Upload logs (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ingest-logs
          path: |
            **/*.log
            **/*.txt
          if-no-files-found: ignore
